### ISSUE TITLE
not getting list of wifi availble

### ISSUE THREAD

**Issue by Manaf-A** [ESP-Provisioning-BLE/esp_provisioning_ble#2]
Not showing list of availble wifi in android

**Comment by adbumanaf** [comment]
is this package searches the nearby wifi availble or the wifi module inside esp32 device itself ...everything ok but not showing any listed wifis available

**Comment by ivanhercaz** [comment]
Please, provide more information of what you are trying in your code to get the available WiFi and the stacktraces/logs to help you more.

**Comment by adbumanaf** [comment]
iam try to run the example code he provided in debug mode this app woks perfectly but in release or profile mode the wifi are storing properly in variable founded networks but not showing properly in the ui part .when ever i try to click scan wifi this error isshowing in log I/flutter (32143): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (32143): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'.but working perfectly in debug mode

**Comment by adbumanaf** [comment]
what is the possible error I/flutter (29411): #0      Flexible.applyParentData (package:flutter/src/widgets/basic.dart:5196)
I/flutter (29411): #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6249)
I/flutter (29411): #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6270)
I/flutter (29411): #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6154)
I/flutter (29411): #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
I/flutter (29411): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
I/flutter (29411): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
I/flutter (29411): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (29411): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
I/flutter (29411): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
I/flutter (29411): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
I/flutter (29411): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (29411): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
I/flutter (29411): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
I/flutter (29411): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
I/flutter (29411): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
I/flutter (29411): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
I/flutter (29411): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
I/flutter (29411): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
I/flutter (29411): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
I/flutter (29411): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
I/flutter (29411): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
I/flutter (29411): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
I/flutter (29411): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6434)
I/flutter (29411): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #55     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569)
I/flutter (29411): #56     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581)
I/flutter (29411): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
I/flutter (29411): #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6434)
I/flutter (29411): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
I/flutter (29411): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3701)
I/flutter (29411): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (29411): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
I/flutter (29411): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
I/flutter (29411): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
I/flutter (29411): #68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
I/flutter (29411): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
I/flutter (29411): #70     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779)
I/flutter (29411): #71     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916)
I/flutter (29411): #72     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
I/flutter (29411): #73     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
I/flutter (29411): #74     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
I/flutter (29411): #75     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
I/flutter (29411): #76     _invoke (dart:ui/hooks.dart:170)
I/flutter (29411): #77     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
I/flutter (29411): #78     _drawFrame (dart:ui/hooks.dart:140)
I/flutter (29411): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (29411): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (29411): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (29411): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (29411): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (29411): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

**Comment by ogabrielinacio** [comment]
You're correct; I'm sorry for that. In release mode, the UI breaks, and the screen stays like this. 
![Screenshot_20231102_083033](https://github.com/ogabrielinacio/esp_provisioning_ble/assets/62192403/e41f008f-16cc-4011-9484-138a032a4f9d)


I'll do my best to fix this issue. Thanks for showing it to me.
Tested on: Samsung Galaxy S10+

**Comment by adbumanaf** [comment]
hey i fixed that ..... in your shared folder there is a scanlist.dart file
.in that file your are using expanded widget that causing the problem ...

**Comment by ogabrielinacio** [comment]
Hey @adbumanaf 
I updated the package's example to a new version. Is that your comment? The scan list is an expanded widget, and in the 'ble_wifi_view,' its parent is a SizedBox, not a Column, Row, or Flex.
https://github.com/ogabrielinacio/esp_provisioning_ble/commit/6ccd1447d79ed0fc1c4edb44dd378239fb165a7b

**Comment by adbumanaf** [comment]
is it possible to send coustom data to a particular endpoint using your
package .my requirement is after or before wifi crendentials proivising is
done.is the wifi connected i want to send a some data to esp to a
particular end point.is that possible .if yes can you help me
